CREATE TABLE PELICULA 
	(COD_PELI CHAR(5 BYTE), 
	TITULO VARCHAR2(70 CHAR) NOT NULL,
	ANYO NUMBER(4,0), 
	DURACION NUMBER(4,0) NOT NULL, 
	COD_LIB CHAR(5 BYTE), 
	DIRECTOR VARCHAR2(70 CHAR), 
	CHECK (duracion > 0), 
	CONSTRAINT PK_PELICULA PRIMARY KEY (COD_PELI),
	CONSTRAINT FK_PELICULA_LIBRO FOREIGN KEY (COD_LIB)
	  REFERENCES LIBRO (COD_LIB)); 
      
CREATE TABLE LIBRO 
	(COD_LIB CHAR(5 BYTE), 
	TITULO VARCHAR2(70 CHAR) NOT NULL, 
	ANYO NUMBER(4,0), 
	AUTOR VARCHAR2(80 CHAR) NOT NULL, 
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIB));

CREATE TABLE ACTOR
    (COD_ACT CHAR(5 BYTE),
    NOMBRE VARCHAR2(70 CHAR) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    NOM_PAIS VARCHAR2(20 CHAR) NOT NULL,
    CONSTRAINT PK_ACTOR PRIMARY KEY (COD_ACT));
    
CREATE TABLE ACTUA
    (COD_ACT CHAR(5 BYTE),
    COD_PELI CHAR(5 BYTE),
    PAPEL VARCHAR2(10 CHAR) NOT NULL,
    CONSTRAINT PK_ACTUA PRIMARY KEY (COD_ACT, COD_PELI),
    CONSTRAINT FK_ACTUA_ACTOR FOREIGN KEY(COD_ACT) REFERENCES ACTOR (COD_ACT),
    CONSTRAINT FK_ACTUA_PELICULA FOREIGN KEY (COD_PELI) REFERENCES PELICULA (COD_PELI),
    CHECK (PAPEL IN('Principal', 'Secundario')));
    
    
INSERT INTO LIBRO(cod_lib, titulo, anyo, autor)
    SELECT * FROM CS_LIBRO;
    
INSERT INTO PELICULA(cod_peli, titulo, anyo, duracion, cod_lib, director)
    SELECT * FROM CS_PELICULA WHERE ANYO>2000;
    
INSERT INTO ACTOR(COD_ACT, NOMBRE, FECHA_NAC, NOM_PAIS)
SELECT A.COD_ACT, A.NOMBRE, A.FECHA_NAC, P.NOMBRE
FROM CS_

INSERT INTO ACTUA(COD_PELI, COD_ACT, PAPEL)
SELECT * FROM CS_ACTUA WHERE CS_ACTUA.COD_PELI IN(SELECT COD_PELI FROM CS_PELICULA WHERE ANYO>2000);
    
