//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BikeClubLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class SomeDaysEvent : Event
	{
        private SomeDaysEvent e5;

        public SomeDaysEvent(SomeDaysEvent e5)
        {
            this.e5 = e5;
        }

        public virtual DateTime FinishDate
		{
			get;
			set;
		}

		public virtual ICollection<Route> Routes
		{
			get;
			set;
		}

	}
}

