//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace BikeClubLib.Entities
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class Club
	{
		public double Quota
		{
			get;
			set;
		}

		public string Name
		{
			get;
			set;
		}

		public virtual ICollection<Member> Members
		{
			get;
			set;
		}

		public virtual Member ActualPresident
		{
			get;
			set;
		}

		public virtual ICollection<Member> Vocals
		{
			get;
			set;
		}

		public virtual ICollection<Election> Elections
		{
			get;
			set;
		}

		public virtual Member Treasurer
		{
			get;
			set;
		}

	}
}

